### ISSUE TITLE
ScriptException: Exception invoking drawImage

### ISSUE THREAD

**Issue by DeborahAnn032** [HtmlUnit/htmlunit-android#13] opened 2022-12-08 15:15 UTC
I am simply try to get a webpage:

    private final static String LOGIN_URL = "https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin";
        private final static WebClient webClient = new WebClient(BrowserVersion.FIREFOX);
        java.util.logging.Logger.getLogger("com.gargoylesoftware.htmlunit").setLevel(java.util.logging.Level.OFF);
        java.util.logging.Logger.getLogger("org.apache.http").setLevel(java.util.logging.Level.OFF);
        final HtmlPage page = webClient.getPage(LOGIN_URL);

However this is the exception I get at runtime:

      ======= EXCEPTION START ========
        Exception class=[java.lang.RuntimeException]
        com.gargoylesoftware.htmlunit.ScriptException: Exception invoking drawImage
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:1001)
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:928)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:900)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
            at com.gargoylesoftware.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1496)
            at com.gargoylesoftware.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4)
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
            at com.gargoylesoftware.htmlunit.html.DomElement.fireEvent(DomElement.java:1496)
            at com.gargoylesoftware.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:949)
            at com.gargoylesoftware.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
            at com.gargoylesoftware.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:342)
            at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:710)
            at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:592)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:510)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:417)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:555)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:537)
            at com.test.xxx.thread.PTCThread.run(PTCThread.java:58)
         Caused by: java.lang.RuntimeException: Exception invoking drawImage
            at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:238)
            at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:405)
            at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1876)
            at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1053)
            at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:335)
            at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3916)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:921)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:984)
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590) 
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349) 
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:928) 
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:900) 
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620) 
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613) 
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342) 
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379) 
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173) 
            at com.gargoylesoftware.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1496) 
            at com.gargoylesoftware.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4) 
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590) 
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484) 
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349) 
            at com.gargoylesoftware.htmlunit.html.DomElement.fireEvent(DomElement.java:1496) 
            at com.gargoylesoftware.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:949) 
            at com.gargoylesoftware.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319) 
            at com.gargoylesoftware.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165) 
            at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:342) 
            at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:710) 
            at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:592) 
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:510) 
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:417) 
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:555) 
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:537) 
            at com.test.xxx.thread.PTCThread.run(PTCThread.java:58) 
         Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
            at com.gargoylesoftware.htmlunit.html.HtmlImage.readImageIfNeeded(HtmlImage.java:702)
    2022-12-05 08:28:08.823 14255-14815/com.test.xxx E/JavaScriptErrorListener:     at com.gargoylesoftware.htmlunit.html.HtmlImage.getImageReader(HtmlImage.java:619)
            at com.gargoylesoftware.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.drawImage(CanvasRenderingContext2D.java:410)
            at java.lang.reflect.Method.invoke(Native Method)
            at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:215)
            	... 36 more
         Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.imageio.ImageIO" on path: DexPathList[[zip file "/data/app/~~uPm2D4x2H8UJPMnJkCz-fQ==/com.test.xxx-7vAaguDgQshpcmtUKuBo6g==/base.apk"],nativeLibraryDirectories=[/data/app/~~uPm2D4x2H8UJPMnJkCz-fQ==/com.test.xxx-7vAaguDgQshpcmtUKuBo6g==/lib/arm64, /system/lib64]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
            	... 41 more
        Enclosed exception: 
        java.lang.RuntimeException: Exception invoking drawImage
            at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:238)
            at net.sourceforge.htmlunit.corejs.javascript.FunctionObject.call(FunctionObject.java:405)
            at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpretLoop(Interpreter.java:1876)
            at net.sourceforge.htmlunit.corejs.javascript.Interpreter.interpret(Interpreter.java:1053)
            at net.sourceforge.htmlunit.corejs.javascript.InterpretedFunction.call(InterpretedFunction.java:89)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.doTopCall(ContextFactory.java:392)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.doTopCall(HtmlUnitContextFactory.java:335)
            at net.sourceforge.htmlunit.corejs.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3916)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$3.doRun(JavaScriptEngine.java:921)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine$HtmlUnitContextAction.run(JavaScriptEngine.java:984)
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:928)
            at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.callFunction(JavaScriptEngine.java:900)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2620)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.executeJavaScriptFunction(HtmlPage.java:2613)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeEventListeners(EventListenersContainer.java:342)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventListenersContainer.executeAtTargetListeners(EventListenersContainer.java:379)
            at com.gargoylesoftware.htmlunit.javascript.host.event.EventTarget.fireEvent(EventTarget.java:173)
            at com.gargoylesoftware.htmlunit.html.DomElement.lambda$fireEvent$0(DomElement.java:1496)
            at com.gargoylesoftware.htmlunit.html.DomElement$$ExternalSyntheticLambda0.run(Unknown Source:4)
            at net.sourceforge.htmlunit.corejs.javascript.Context.call(Context.java:590)
            at net.sourceforge.htmlunit.corejs.javascript.ContextFactory.call(ContextFactory.java:484)
            at com.gargoylesoftware.htmlunit.javascript.HtmlUnitContextFactory.callSecured(HtmlUnitContextFactory.java:349)
            at com.gargoylesoftware.htmlunit.html.DomElement.fireEvent(DomElement.java:1496)
            at com.gargoylesoftware.htmlunit.html.HtmlImage.fireEvent(HtmlImage.java:949)
            at com.gargoylesoftware.htmlunit.html.HtmlImage.doOnLoad(HtmlImage.java:319)
            at com.gargoylesoftware.htmlunit.html.HtmlImage$1.execute(HtmlImage.java:165)
            at com.gargoylesoftware.htmlunit.html.HtmlPage.initialize(HtmlPage.java:342)
            at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:710)
    2022-12-05 08:28:08.823 14255-14815/com.test.xxx E/JavaScriptErrorListener:     at com.gargoylesoftware.htmlunit.WebClient.loadWebResponseInto(WebClient.java:592)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:510)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:417)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:555)
            at com.gargoylesoftware.htmlunit.WebClient.getPage(WebClient.java:537)
            at com.test.xxx.thread.PTCThread.run(PTCThread.java:58)
         Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
            at com.gargoylesoftware.htmlunit.html.HtmlImage.readImageIfNeeded(HtmlImage.java:702)
            at com.gargoylesoftware.htmlunit.html.HtmlImage.getImageReader(HtmlImage.java:619)
            at com.gargoylesoftware.htmlunit.javascript.host.canvas.CanvasRenderingContext2D.drawImage(CanvasRenderingContext2D.java:410)
            at java.lang.reflect.Method.invoke(Native Method)
            at net.sourceforge.htmlunit.corejs.javascript.MemberBox.invoke(MemberBox.java:215)
            	... 36 more
         Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.imageio.ImageIO" on path: DexPathList[[zip file "/data/app/~~uPm2D4x2H8UJPMnJkCz-fQ==/com.test.xxx-7vAaguDgQshpcmtUKuBo6g==/base.apk"],nativeLibraryDirectories=[/data/app/~~uPm2D4x2H8UJPMnJkCz-fQ==/com.test.xxx-7vAaguDgQshpcmtUKuBo6g==/lib/arm64, /system/lib64]]
            at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
            at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
            	... 41 more
        == CALLING JAVASCRIPT ==
          function () {
              c.drawImage(a, 0, 0), Modernizr.addTest("todataurljpeg", function () {
                  return b.toDataURL("image/jpeg").indexOf("data:image/jpeg") === 0;
              }), Modernizr.addTest("todataurlwebp", function () {
                  return b.toDataURL("image/webp").indexOf("data:image/webp") === 0;
              });
          }
        ======= EXCEPTION END ========

The issue seems to be the fact that it's not able to find the class imageIO in the DexPathList, am I correct? If so, how to fix this?

**Comment by rbri** [comment] 2022-12-08 15:37
Thanks for the report, will work on this soon

**Comment by rbri** [comment] 2022-12-09 07:46
this is an duplicate of #3

There is a imageio class part of the interface - i have no idea how to solve this without breaking the interface.
Will think about a way to do this....

**Comment by DeborahAnn032** [comment] 2022-12-09 13:47
I see! Maybe dynamically loading the class could save you from breaking the interface?

**Comment by rbri** [comment] 2022-12-09 16:22
yes that's more or less the plan at what i'm already doing at other places. The problem here is the method 

    public ImageReader getImageReader()

The class is used when the dom/page (containing an image) is constructed.
This means i have to replace the method with something that does not use imageio.

**Comment by DeborahAnn032** [comment] 2022-12-09 19:46
I see. Just a temporary fix - you could ignore the image for the time being? Until you replace that method.

**Comment by rbri** [comment] 2023-01-14 16:37
@DeborahAnn032
Can you please try with htmlunit-android 3.0.0-SNAPSHOT and report your results here.

**Comment by DeborahAnn032** [comment] 2023-01-15 19:25
`    implementation group: 'net.sourceforge.htmlunit', name: 'htmlunit-android', version: '3.0.0-SNAPSHOT'
`    
    @rbri sadly with 3.0.0-SNAPSHOT it doesn't find anything, the imports are all "red".

**Comment by rbri** [comment] 2023-01-16 07:30
@DeborahAnn032 thanks, will have a look and come back to you later today

**Comment by rbri** [comment] 2023-01-17 17:21
Yes, but the snapshots are in i different repository. You have to tweak your build file a bit more.

see https://github.com/HtmlUnit/htmlunit at the very bottom

**Comment by DeborahAnn032** [comment] 2023-01-19 08:47
Okay, all done. 
This is what I am getting now:

 ```
E  FATAL EXCEPTION: main
                                                                                                    Process: com.test.xxx, PID: 25840
                                                                                                    java.lang.ExceptionInInitializerError
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784)
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loop(Looper.java:246)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
                                                                                                    Caused by: java.lang.RuntimeException: Processing classConfiguration for class Rangefailed. Reason: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/gargoylesoftware/htmlunit/html/impl/SimpleRange;
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:332)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:193)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:67)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:685)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:701)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:161)
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:305)
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:254)
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:244)
                                                                                                    	at com.test.xxx.thread.MyThread.<clinit>(MyThread.java:31)
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92) 
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784) 
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/gargoylesoftware/htmlunit/html/impl/SimpleRange;
                                                                                                    	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method)
                                                                                                    	at java.lang.reflect.Method.getReturnType(Method.java:148)
                                                                                                    	at java.lang.Class.getDeclaredMethods(Class.java:1883)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:213)
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:193) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:67) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:685) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:701) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:161) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:305) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:254) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:244) 
                                                                                                    	at com.test.xxx.thread.MyThread.<clinit>(MyThread.java:31) 
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92) 
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784) 
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: com.gargoylesoftware.htmlunit.html.impl.SimpleRange
                                                                                                    	at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                                                    	at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method) 
                                                                                                    	at java.lang.reflect.Method.getReturnType(Method.java:148) 
                                                                                                    	at java.lang.Class.getDeclaredMethods(Class.java:1883) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:213) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:193) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:67) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:685) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:701) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:161) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:305) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:254) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:244) 
                                                                                                    	at com.test.xxx.thread.MyThread.<clinit>(MyThread.java:31) 
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92) 
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784) 
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
                                                                                                    Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/w3c/dom/ranges/Range;
                                                                                                    	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method) 
                                                                                                    	at java.lang.reflect.Method.getReturnType(Method.java:148) 
                                                                                                    	at java.lang.Class.getDeclaredMethods(Class.java:1883) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:213) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:193) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:67) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:685) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:701) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:161) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:305) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:254) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:244) 
                                                                                                    	at com.test.xxx.thread.MyThread.<clinit>(MyThread.java:31) 
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92) 
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784) 
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "org.w3c.dom.ranges.Range" on path: DexPathList[[dex file "/data/data/com.test.xxx/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~VGJdI745BJnlg4RkMNVXXw==/com.test.xxx-orqu8vel22l3IbmduIFDFw==/base.apk"],nativeLibraryDirectories=[/data/app/~~VGJdI745BJnlg4RkMNVXXw==/com.test.xxx-orqu8vel22l3IbmduIFDFw==/lib/arm64, /system/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:207)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at java.lang.reflect.Executable.getMethodReturnTypeInternal(Native Method) 
                                                                                                    	at java.lang.reflect.Method.getReturnType(Method.java:148) 
                                                                                                    	at java.lang.Class.getDeclaredMethods(Class.java:1883) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.process(AbstractJavaScriptConfiguration.java:213) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.getClassConfiguration(AbstractJavaScriptConfiguration.java:193) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.AbstractJavaScriptConfiguration.<init>(AbstractJavaScriptConfiguration.java:67) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.<init>(JavaScriptConfiguration.java:685) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.configuration.JavaScriptConfiguration.getInstance(JavaScriptConfiguration.java:701) 
                                                                                                    	at com.gargoylesoftware.htmlunit.javascript.JavaScriptEngine.<init>(JavaScriptEngine.java:161) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:305) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:254) 
                                                                                                    	at com.gargoylesoftware.htmlunit.WebClient.<init>(WebClient.java:244) 
                                                                                                    	at com.test.xxx.thread.MyThread.<clinit>(MyThread.java:31) 
                                                                                                    	at com.test.xxx.service.MyService.onStartCommand(MyService.java:92) 
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:4784) 
                                                                                                    	at android.app.ActivityThread.access$1900(ActivityThread.java:301) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2204) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loop(Looper.java:246) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8633) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130) 
```

**Comment by rbri** [comment] 2023-01-19 16:52
Ok, there is  another set of interface (org.w3c.dom.ranges) not available on Android.
Have to think a bit, will come back to your if this is solved.

**Comment by DeborahAnn032** [comment] 2023-01-23 09:19
Ok, thanks!

**Comment by rbri** [comment] 2023-04-27 06:25
3.1.0 is finally out - and should work now without problems.

Enjoy and report your findings.

**Closed by rbri** 2023-04-27 06:25 UTC
