### ISSUE TITLE
 java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier

### ISSUE THREAD

**Issue by DeborahAnn032** [HtmlUnit/htmlunit-android#28] opened 2023-09-08 10:03 UTC
I am using HtmlUnit on my android project:

        implementation group: 'org.htmlunit', name: 'htmlunit3-android', version: '3.5.0'

I am simply try to get a webpage:

        private final static String LOGIN_URL = "https://sso.pokemon.com/sso/login?locale=en&service=https://www.pokemon.com/us/pokemon-trainer-club/caslogin";
            private final static WebClient webClient = new WebClient(BrowserVersion.FIREFOX);
            java.util.logging.Logger.getLogger("org.apache.http").setLevel(java.util.logging.Level.OFF);
            final HtmlPage page = webClient.getPage(LOGIN_URL);
    

However this is the exception I get at runtime:

```
--------- beginning of crash
2023-09-08 08:42:51.303 11938-17672 AndroidRuntime com.example.port.appn E FATAL EXCEPTION: Thread-2
 Process: com.example.port.appn, PID: 11938
 java.lang.NoSuchFieldError: No static field INSTANCE of type Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; in class Lorg/apache/http/conn/ssl/AllowAllHostnameVerifier; or its superclasses (declaration of 'org.apache.http.conn.ssl.AllowAllHostnameVerifier' appears in /system/framework/framework.jar!classes5.dex)
 at org.apache.http.conn.ssl.SSLConnectionSocketFactory.<clinit>(SSLConnectionSocketFactory.java:151)
 at org.htmlunit.httpclient.HtmlUnitSSLConnectionSocketFactory.buildSSLSocketFactory(HtmlUnitSSLConnectionSocketFactory.java:88)
 at org.htmlunit.HttpWebConnection.configureHttpsScheme(HttpWebConnection.java:675)
 at org.htmlunit.HttpWebConnection.createHttpClientBuilder(HttpWebConnection.java:593)
 at org.htmlunit.HttpWebConnection.getHttpClientBuilder(HttpWebConnection.java:549)
 at org.htmlunit.HttpWebConnection.getResponse(HttpWebConnection.java:175)
 at org.htmlunit.WebClient.getWebResponseOrUseCached(WebClient.java:1668)
 at org.htmlunit.WebClient.loadWebResponseFromWebConnection(WebClient.java:1567)
 at org.htmlunit.WebClient.loadWebResponse(WebClient.java:1491)
 at org.htmlunit.WebClient.getPage(WebClient.java:475)
 at org.htmlunit.WebClient.getPage(WebClient.java:390)
 at org.htmlunit.WebClient.getPage(WebClient.java:528)
 at org.htmlunit.WebClient.getPage(WebClient.java:510)
 at com.port.appn.thread.PTCThread.run(PTCThread.java:59)
2023-09-08 08:42:51.313 4772-4789 BufferQueueProducer surfaceflinger E [com.example.port.appn/com.port.appn.main.MainActivity$_11938#0](id:12a40000001a,api:0,p:-1,c:4772) disconnect: not connected (req=1)
```

**Comment by rbri** [comment] 2023-09-08 10:11
@DeborahAnn032 ok will have a look

**Comment by rbri** [comment] 2023-09-08 10:15
@DeborahAnn032 can you check the file size of your htmlunit3-android-3.5.0.jar

**Comment by DeborahAnn032** [comment] 2023-09-09 07:59
@rbri 
6.037.527 bytes (6 MB on disk)

**Comment by rbri** [comment] 2023-09-09 11:15
Looks correct, you have the shaded one.

The error points to a a problem with the apache http client (which is used by HtmlUnit and also provided by the Android jdk). The android version is old and HtmlUnit uses the new one.
Because of the troubles with this i have shaded the HttpClient and included in the htmlunit3-android-3.x.x.jar. So usually the problem is solved based on this.

Can you try to figure out if you have two jar files in your class path containing org.htmlunit.WebClient?

**Comment by DeborahAnn032** [comment] 2023-09-09 16:55
After I did a clean of the build the issue disappeared. So, as you probably said, it might have been due to duplicates in the class path.

**Comment by rbri** [comment] 2023-09-09 17:26
Puhh, i really like solutions like this one.
Will close this, thanks for the feedback.

**Closed by rbri** 2023-09-09 17:26 UTC
